In [4]:
import cv2
import numpy as np

img = cv2.imread("C:\\Users\\Admin\\Desktop\\RoboVision\\image_color.jpg",cv2.IMREAD_COLOR)
cv2.imshow("image",img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
import cv2
import numpy as np

A = cv2.imread("E:\\VSC_workspace\\robot_vision_lab\\Lab5\\RoboVision\\black_dot.jpg",cv2.IMREAD_COLOR)
cv2.imshow("A",A)

cv2.waitKey(0)

Lh = cv2.imread("E:\\VSC_workspace\\robot_vision_lab\\Lab5\\RoboVision\\horizontal_line.jpg",cv2.IMREAD_COLOR)
cv2.imshow("Lh",Lh)

cv2.waitKey(0)

Lv = cv2.imread("E:\\VSC_workspace\\robot_vision_lab\\Lab5\\RoboVision\\vertical_line.jpg",cv2.IMREAD_COLOR)
cv2.imshow("Lv",Lv)
cv2.waitKey(0)

Ldp = cv2.imread("E:\\VSC_workspace\\robot_vision_lab\\Lab5\\RoboVision\\positive_45.jpg",cv2.IMREAD_COLOR)
cv2.imshow("Ldp",Ldp)
cv2.waitKey(0)

Ldn = cv2.imread("E:\\VSC_workspace\\robot_vision_lab\\Lab5\\RoboVision\\slanted_negative45.jpg",cv2.IMREAD_COLOR)
cv2.imshow("Ldn",Ldn)
cv2.waitKey(0)

cv2.destroyAllWindows()

In [1]:
import cv2
import numpy as np
import math

Lh = cv2.imread("E:\\VSC_workspace\\robot_vision_lab\\Lab5\\RoboVision\\horizontal_line.jpg",cv2.IMREAD_COLOR)
cv2.imshow("Lh",Lh)

cv2.waitKey(0)

gray = cv2.cvtColor(Lh, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray, 50, 150, apertureSize=3)
lines = cv2.HoughLines(edges, 1, np.pi/180, 200)

for r_theta in lines:
    arr = np.array(r_theta[0], dtype=np.float64)
    r, theta = arr
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a*r
    y0 = b*r
    x1 = int(x0 + 1000*(-b))
    y1 = int(y0 + 1000*(a))
    x2 = int(x0 - 1000*(-b))
    y2 = int(y0 - 1000*(a))

    cv2.line(Lh, (x1, y1), (x2, y2), (0, 0, 255), 2)
    print("Spatial coordinates are: ",(x1,y1)," ",(x2,y2)," ")
print("The orientation is: ",math.atan((y2-y1)/(x2-x1)))  

cv2.imwrite('linesDetected_Lh.jpg', Lh)

cv2.destroyAllWindows()


Spatial coordinates are:  (-1000, 155)   (999, 156)  
Spatial coordinates are:  (-1000, 164)   (999, 165)  
The orientation is:  0.0005002500833333083


In [5]:
import cv2
#import numpy as np
A_gray = cv2.imread("E:\\VSC_workspace\\robot_vision_lab\\Lab5\\RoboVision\\blackdot_matrix.jpg",cv2.IMREAD_GRAYSCALE)
cv2.imshow("A_gray",A_gray)
cv2.waitKey(0)

Lh_gray = cv2.imread("E:\\VSC_workspace\\robot_vision_lab\\Lab5\\RoboVision\\horizontal_line.jpg",cv2.IMREAD_GRAYSCALE)
cv2.imshow("Lh_gray",Lh_gray)
cv2.waitKey(0)

Lv_gray = cv2.imread("E:\\VSC_workspace\\robot_vision_lab\\Lab5\\RoboVision\\vertical_line.jpg",cv2.IMREAD_GRAYSCALE)
cv2.imshow("Lv_gray",Lv_gray)
cv2.waitKey(0)

Ldp_gray = cv2.imread("E:\\VSC_workspace\\robot_vision_lab\\Lab5\\RoboVision\\positive_45.jpg",cv2.IMREAD_GRAYSCALE)
cv2.imshow("Ldp_gray",Ldp_gray)
cv2.waitKey(0)

Ldn_gray = cv2.imread("E:\\VSC_workspace\\robot_vision_lab\\Lab5\\RoboVision\\slanted_negative45.jpg",cv2.IMREAD_GRAYSCALE)
cv2.imshow("Ldn_gray",Ldn_gray)
cv2.waitKey(0)

cv2.destroyAllWindows()

In [8]:
import cv2
import numpy as np
import math

Lh = cv2.imread("E:\\VSC_workspace\\robot_vision_lab\\Lab5\\RoboVision\\black_dot.jpg",cv2.IMREAD_COLOR)
cv2.imshow("Lh",Lh)

cv2.waitKey(0)

gray = cv2.cvtColor(Lh, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray, 50, 150, apertureSize=3)
lines = cv2.HoughLines(edges, 1, np.pi/180, 200)

for r_theta in lines:
    arr = np.array(r_theta[0], dtype=np.float64)
    r, theta = arr
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a*r
    y0 = b*r
    x1 = int(x0 + 1000*(-b))
    y1 = int(y0 + 1000*(a))
    x2 = int(x0 - 1000*(-b))
    y2 = int(y0 - 1000*(a))

    cv2.line(Lh, (x1, y1), (x2, y2), (0, 0, 255), 2)
    print("Spatial coordinates are: ",(x1,y1)," ",(x2,y2)," ")
print("The orientation is: ",math.atan((y2-y1)/(x2-x1)))  

cv2.imwrite('linesDetected_Lh.jpg', Lh)

cv2.destroyAllWindows()


TypeError: 'NoneType' object is not iterable

: 

In [5]:
import cv2
import numpy as np
import math

Lv = cv2.imread("E:\\VSC_workspace\\robot_vision_lab\\Lab5\\RoboVision\\vertical_line.jpg",cv2.IMREAD_COLOR)
cv2.imshow("Lv",Lv)
cv2.waitKey(0)


gray = cv2.cvtColor(Lv, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray, 50, 150, apertureSize=3)
lines = cv2.HoughLines(edges, 1, np.pi/180, 200)

for r_theta in lines:
    arr = np.array(r_theta[0], dtype=np.float64)
    r, theta = arr
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a*r
    y0 = b*r
    x1 = int(x0 + 1000*(-b))
    y1 = int(y0 + 1000*(a))
    x2 = int(x0 - 1000*(-b))
    y2 = int(y0 - 1000*(a))

    cv2.line(Lv, (x1, y1), (x2, y2), (0, 0, 255), 2)
    print("Spatial coordinates are: ",(x1,y1)," ",(x2,y2)," ")
#print("The orientation is: ",math.atan((y2-y1)/(x2-x1)))  
#The orientation will be atan of pi/2 which will be undefined and throw an error

cv2.imwrite('linesDetected_Lv.jpg', Lv)

Spatial coordinates are:  (302, 1000)   (302, -1000)  
Spatial coordinates are:  (324, 1000)   (324, -1000)  


True

In [19]:
import cv2
import numpy as np
import math

Ldp = cv2.imread("E:\\VSC_workspace\\robot_vision_lab\\Lab5\\RoboVision\\positive_45.jpg",cv2.IMREAD_COLOR)
cv2.imshow("Ldp",Ldp)
cv2.waitKey(0)

gray = cv2.cvtColor(Ldp, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray, 50, 150, apertureSize=3)
lines = cv2.HoughLines(edges, 1, np.pi/180, 200)

for r_theta in lines:
    arr = np.array(r_theta[0], dtype=np.float64)
    r, theta = arr
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a*r
    y0 = b*r
    x1 = int(x0 + 1000*(-b))
    y1 = int(y0 + 1000*(a))
    x2 = int(x0 - 1000*(-b))
    y2 = int(y0 - 1000*(a))

    cv2.line(Ldp, (x1, y1), (x2, y2), (0, 0, 255), 2)
    print("Spatial coordinates are: ",(x1,y1)," ",(x2,y2)," ")
print("The orientation is: ",math.atan(abs((y2-y1)/(x2-x1))))  

cv2.imwrite('linesDetected_Ldp.jpg', Ldp)

cv2.destroyAllWindows()


Spatial coordinates are:  (-512, 901)   (901, -512)  
Spatial coordinates are:  (-502, 911)   (911, -502)  
The orientation is:  0.7853981633974483


In [8]:
import cv2
import numpy as np
import math

Ldn = cv2.imread("E:\\VSC_workspace\\robot_vision_lab\\Lab5\\RoboVision\\slanted_negative45.jpg",cv2.IMREAD_COLOR)
cv2.imshow("Ldn",Ldn)
cv2.waitKey(0)

gray = cv2.cvtColor(Ldn, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray, 50, 150, apertureSize=3)
lines = cv2.HoughLines(edges, 1, np.pi/180, 200)

for r_theta in lines:
    arr = np.array(r_theta[0], dtype=np.float64)
    r, theta = arr
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a*r
    y0 = b*r
    x1 = int(x0 + 1000*(-b))
    y1 = int(y0 + 1000*(a))
    x2 = int(x0 - 1000*(-b))
    y2 = int(y0 - 1000*(a))

    cv2.line(Ldn, (x1, y1), (x2, y2), (0, 0, 255), 2)
    print("Spatial coordinates are: ",(x1,y1)," ",(x2,y2)," ")
print("The orientation is: ",math.atan(abs((y2-y1)/(x2-x1))))  

cv2.imwrite('linesDetected_Ldn.jpg', Ldn)

cv2.destroyAllWindows()

Spatial coordinates are:  (-702, -711)   (711, 702)  
Spatial coordinates are:  (-710, -703)   (703, 710)  
The orientation is:  0.7853981633974483


In [5]:
import cv2
import numpy as np
A_gray = cv2.imread("E:\\VSC_workspace\\robot_vision_lab\\Lab5\\RoboVision\\black_dot.jpg",cv2.IMREAD_GRAYSCALE)
cv2.imshow("A_gray",A_gray)
cv2.waitKey(0)

kernel = np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1]])
#print(kernel)

A_gray_conv = cv2.filter2D(A_gray,-1,kernel)
cv2.imshow("Convoluted A image",A_gray_conv)
cv2.waitKey(0)


cv2.destroyAllWindows()

In [7]:
import cv2
import numpy as np
Lh_gray = cv2.imread("E:\\VSC_workspace\\robot_vision_lab\\Lab5\\RoboVision\\horizontal_line.jpg",cv2.IMREAD_GRAYSCALE)
cv2.imshow("Lh_gray",Lh_gray)
cv2.waitKey(0)
kernel = np.array([[-1,-1,-1],[2,2,2],[-1,-1,-1]])
#print(kernel)

Lh_gray_conv = cv2.filter2D(Lh_gray,-1,kernel)
cv2.imshow("Convoluted Lh image",Lh_gray_conv)
cv2.waitKey(0)

cv2.destroyAllWindows()
0

In [3]:
import cv2
import numpy as np
Lv_gray = cv2.imread("E:\\VSC_workspace\\robot_vision_lab\\Lab5\\RoboVision\\vertical_line.jpg",cv2.IMREAD_GRAYSCALE)
cv2.imshow("Lv_gray",Lv_gray)
cv2.waitKey(0)

kernel = np.array([[-1,2,-1],[-1,2,-1],[-1,2,-1]])
#print(kernel)

Lv_gray_conv = cv2.filter2D(Lv_gray,-1,kernel)
cv2.imshow("Convoluted Lv image",Lv_gray_conv)
cv2.waitKey(0)

cv2.destroyAllWindows()



In [6]:
import cv2
import numpy as np
Ldp_gray = cv2.imread("E:\\VSC_workspace\\robot_vision_lab\\Lab5\\RoboVision\\positive_45.jpg",cv2.IMREAD_GRAYSCALE)
cv2.imshow("Ldp_gray",Ldp_gray)
cv2.waitKey(0)

kernel = np.array([[-1,-1,2],[-1,2,-1],[2,-1,-1]])
#print(kernel)

Ldp_gray_conv = cv2.filter2D(Ldp_gray,-1,kernel)
cv2.imshow("Convoluted Ldp image",Ldp_gray_conv)
cv2.waitKey(0)

cv2.destroyAllWindows()

In [7]:
import cv2
import numpy as np
Ldn_gray = cv2.imread("E:\\VSC_workspace\\robot_vision_lab\\Lab5\\RoboVision\\slanted_negative45.jpg",cv2.IMREAD_GRAYSCALE)
cv2.imshow("Ldn_gray",Ldn_gray)
cv2.waitKey(0)

kernel = np.array([[2,-1,-1],[-1,2,-1],[-1,-1,2]])
#print(kernel)

Ldn_gray_conv = cv2.filter2D(Ldn_gray,-1,kernel)
cv2.imshow("Convoluted Ldn image",Ldn_gray_conv)
cv2.waitKey(0)

cv2.destroyAllWindows()


In [2]:
import cv2
import numpy as np
A_gray = cv2.imread("E:\\VSC_workspace\\robot_vision_lab\\Lab5\\RoboVision\\black_dot.jpg",cv2.IMREAD_GRAYSCALE)
cv2.imshow("A_gray",A_gray)
cv2.waitKey(0)

print(A_gray)

for i in A_gray:
    for j in i:
        if(j!=255):
            print(j)



#kernel = np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1]])
#print(kernel)

#A_gray_conv = cv2.filter2D(A_gray,-1,kernel)
#cv2.imshow("Convoluted A image",A_gray_conv)
#cv2.waitKey(0)


cv2.destroyAllWindows()

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
252
254
246
246
246
254
248
244
254
247
250
244
246
248
246
249
254
253
250
254
229
242
254
247
179
12
4
0
155
231
244
248
248
182
16
0
0
6
0
139
247
254
244
216
11
0
1
13
0
0
10
249
253
240
249
2
3
20
0
5
0
2
251
254
245
246
240
0
0
0
2
0
7
0
248
250
154
3
0
8
11
0
0
251
250
249
251
224
138
2
0
0
12
183
241
254
250
253
251
248
254
236
245
254
253
247
249
248
251
235
