In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
image = cv2.imread('Huggbees.jpg')
gray_image = cv2.imread('Huggbees.jpg',0)
png = cv2.imread('C:\\Users\\Shree\\Desktop\\Programs\\VSC\\CSE4082\\09-09-2022\\Huggbees.png')
tiff = cv2.imread('C:\\Users\\Shree\\Desktop\\Programs\\VSC\\CSE4082\\09-09-2022\\Huggbees.tiff')
jpeg = cv2.imread('C:\\Users\\Shree\\Desktop\\Programs\\VSC\\CSE4082\\09-09-2022\\Huggbees.jpg')
png_grayscaled = cv2.cvtColor(png, 0)
tiff_grayscaled = cv2.cvtColor(tiff, 0)
jpeg_grayscaled = cv2.cvtColor(jpeg, 0)
# Convert the grayscale image into rgb, cmyk
png_rgb = cv2.cvtColor(png_grayscaled,0)
tiff_rgb = cv2.cvtColor(tiff_grayscaled,0)
jpeg_rgb = cv2.cvtColor(jpeg_grayscaled, 0)


def image_to_cymk(img):
    i = img.astype(np.float64)/255.
    c = 1-i[:, :, 0]
    m = 1-i[:, :, 1]
    y = 1-i[:, :, 2]
    k = 1-np.min(i, axis=2)
    return np.dstack((c, m, y, k))


png_cymk = image_to_cymk(png_rgb)
tiff_cymk = image_to_cymk(tiff_rgb)
jpeg_cymk = image_to_cymk(jpeg_rgb)


In [2]:
cv2.imshow('Original', image)
cv2.waitKey(0)
cv2.imshow('Grayscale', gray_image)
cv2.waitKey(0)
cv2.imshow('PNG_CYMK', png_cymk)
cv2.waitKey(0)
cv2.imshow('TIFF_CYMK', tiff_cymk)
cv2.waitKey(0)
cv2.imshow('JPEG_CYMK', jpeg_cymk)
cv2.waitKey(0)
cv2.imshow('PNG_RGB', png_rgb)
cv2.waitKey(0)
cv2.imshow('TIFF_RGB', tiff_rgb)
cv2.waitKey(0)
cv2.imshow('JPEG_RGB', jpeg_rgb)
cv2.waitKey(0)

cv2.destroyAllWindows()

In [3]:
def block_segmentation(image, blocks):
    block_size = blocks.shape[0]
    block_segmented = np.zeros(image.shape)
    for i in range(0, image.shape[0] - block_size, block_size):
        for j in range(0, image.shape[1] - block_size, block_size):
            block = image[i:i + block_size, j:j +  block_size]
            block_segmented[i:i + block_size, j:j + block_size] = np.mean(block)
    return block_segmented


blocks = np.array([[0, 0], [0, 1], [1, 0], [1,1]])

In [4]:
print("\nRGB")
print(block_segmentation(png_rgb, blocks))
print(block_segmentation(tiff_rgb, blocks))
print(block_segmentation(jpeg_rgb, blocks))
print("\nCYMK")
print(block_segmentation(png_cymk, blocks))
print(block_segmentation(tiff_cymk, blocks))
print(block_segmentation(jpeg_cymk, blocks))


RGB
[[[87.65625 87.65625 87.65625 87.65625]
  [87.65625 87.65625 87.65625 87.65625]
  [87.65625 87.65625 87.65625 87.65625]
  ...
  [ 0.       0.       0.       0.     ]
  [ 0.       0.       0.       0.     ]
  [ 0.       0.       0.       0.     ]]

 [[87.65625 87.65625 87.65625 87.65625]
  [87.65625 87.65625 87.65625 87.65625]
  [87.65625 87.65625 87.65625 87.65625]
  ...
  [ 0.       0.       0.       0.     ]
  [ 0.       0.       0.       0.     ]
  [ 0.       0.       0.       0.     ]]

 [[87.65625 87.65625 87.65625 87.65625]
  [87.65625 87.65625 87.65625 87.65625]
  [87.65625 87.65625 87.65625 87.65625]
  ...
  [ 0.       0.       0.       0.     ]
  [ 0.       0.       0.       0.     ]
  [ 0.       0.       0.       0.     ]]

 ...

 [[83.625   83.625   83.625   83.625  ]
  [83.625   83.625   83.625   83.625  ]
  [83.625   83.625   83.625   83.625  ]
  ...
  [ 0.       0.       0.       0.     ]
  [ 0.       0.       0.       0.     ]
  [ 0.       0.       0.       0.     ]